server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /contact-form {
        try_files /contact-form.html =404;
    }

    location = /privacy-policy {
        try_files /privacy-policy.html =404;
    }

    location = /tos {
        try_files /tos.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
